export const ANIMAL_DATA = [
  {
    location: {
      latitude: 40.445371,
      longitude: -3.734983,
    },
    species: "ave",
    birth: "2020-01-07",
    gender: "macho",
    size: "pequeño",
    weight: "0.5kg",
    history: "Mi dueño me echo de casa por hacer mucho ruido.",
    personality: ["alegre", "ruidoso"],
    city: "madrid",
    name: "alfred",
    imageUrl:
      "https://lafeber.com/pet-birds/wp-content/uploads/2018/06/Blue-and-Gold-Macaw-300x300.jpg",
    health: {
      vaccinated: true,
      dewormed: true,
      healthy: true,
      sterilized: true,
      registered: true,
      microchip: true,
      info: "ave feliz!",
    },
    adoption: {
      requirements: {
        otherAnimals: true,
        coexistsWithAnimaltype: "perro, gato, chinchilla",
        friendly: false,
        animalNeeds: ["jaula", "comida"],
        animalExpensesMonthly: 10,
        animalFood: "pipas",
      },
      adoptionFee: 125,
      shipToAnotherCity: "ninguno",
    },
  },

  {
    location: {
      latitude: 40.404998,
      longitude: -3.697989,
    },
    species: "gato",
    birth: "2017-04-15",
    gender: "macho",
    size: "pequeño",
    weight: "3kg",
    history: "Chinchilla criada en un circo. Puede atravesar aros de fuego",
    personality: ["timido", "bueno con niños"],
    city: "madrid",
    name: "ratatouille",
    imageUrl:
      "https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    health: {
      vaccinated: true,
      dewormed: true,
      healthy: true,
      sterilized: false,
      registered: false,
      microchip: false,
      info: "Chinchilla agente secreto!",
    },
    adoption: {
      requirements: {
        otherAnimals: false,
        coexistsWithAnimaltype: "ninguno",
        friendly: false,
        animalNeeds: ["comida", "jaula"],
        animalExpensesMonthly: 10,
        animalFood: "lechuga",
      },
      adoptionFee: 30,
      shipToAnotherCity: "no se envia",
    },
  },
  {
    location: {
      latitude: 40.443749,
      longitude: -3.684413,
    },
    species: "gato",
    birth: "2016-04-28",
    gender: "macho",
    size: "pequeño",
    weight: "3kg",
    history: "Gato rechazado por rompar muchos vasos.",
    personality: ["timido", "alegre"],
    city: "madrid",
    name: "firulais",
    imageUrl:
      "https://www.pasadenastarnews.com/wp-content/uploads/2019/04/A471529_Alice_b-1.jpg",
    health: {
      vaccinated: true,
      dewormed: true,
      healthy: true,
      sterilized: false,
      registered: false,
      microchip: false,
      info: "Gato bipolar.",
    },
    adoption: {
      requirements: {
        otherAnimals: true,
        coexistsWithAnimaltype: "perro, pajaro, chinchilla",
        friendly: false,
        animalNeeds: ["comida", "jaula", "jardin"],
        animalExpensesMonthly: 30,
        animalFood: "comida para gatos, atun",
      },
      adoptionFee: 130,
      shipToAnotherCity: "no se envia",
    },
  },
  {
    location: {
      latitude: 40.432746,
      longitude: -3.6952,
    },
    species: "perro",
    birth: "2019-02-15",
    gender: "macho",
    size: "grande",
    weight: "30kg",
    history:
      "Mi dueño tenia miedo que me entrara hambre y me lo comiera. Buscando nueva familia",
    personality: ["alegre", "jugueton"],
    city: "madrid",
    name: "lucky",
    imageUrl:
      "https://thepuppyplace.org/wp-content/uploads/2018/09/Yellow-Labrador-Looking.jpg",
    health: {
      vaccinated: true,
      dewormed: true,
      healthy: true,
      sterilized: false,
      registered: false,
      microchip: false,
      info: "Perro hiperactivo y feliz!",
    },
    adoption: {
      requirements: {
        otherAnimals: false,
        coexistsWithAnimaltype: "ninguno",
        friendly: false,
        animalNeeds: ["jardin", "comida"],
        animalExpensesMonthly: 100,
        animalFood: "comida para perros",
      },
      adoptionFee: 0,
      shipToAnotherCity: "sevilla, valencia, bilbao",
    },
  },
];
