export const TOOGLE_HIDDEN_PASS = "TOOGLE_HIDDEN_PASS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCHING_ANIMALS_PENDING = "FETCHING_ANIMALS_PENDING";
export const FETCHING_ANIMALS_SUCCESS = "FETCHING_ANIMALS_SUCCESS";
export const FETCHING_ANIMALS_FAILED = "FETCHING_ANIMALS_FAILED";
